export const colorList: { name: string; hex: string }[] = [
  { name: 'Rojo', hex: '#FF0000' },
  { name: 'Verde', hex: '#00FF00' },
  { name: 'Azul', hex: '#0000FF' },
  { name: 'Amarillo', hex: '#FFFF00' },
  { name: 'Cian', hex: '#00FFFF' },
  { name: 'Magenta', hex: '#FF00FF' },
  { name: 'Naranja', hex: '#FFA500' },
  { name: 'Rosa', hex: '#FFC0CB' },
  { name: 'Marrón', hex: '#A52A2A' },
  { name: 'Gris', hex: '#808080' },
  { name: 'Negro', hex: '#000000' },
  { name: 'Blanco', hex: '#FFFFFF' },
  { name: 'Violeta', hex: '#8A2BE2' },
  { name: 'Índigo', hex: '#4B0082' },
  { name: 'Turquesa', hex: '#40E0D0' },
  { name: 'Lavanda', hex: '#E6E6FA' },
  { name: 'Salmón', hex: '#FA8072' },
  { name: 'Coral', hex: '#FF7F50' },
  { name: 'Oro', hex: '#FFD700' },
  { name: 'Plata', hex: '#C0C0C0' },
  { name: 'Azul cielo', hex: '#87CEEB' },
  { name: 'Verde lima', hex: '#00FF00' },
  { name: 'Azul marino', hex: '#000080' },
  { name: 'Verde oliva', hex: '#808000' },
  { name: 'Azul acero', hex: '#4682B4' },
  { name: 'Verde esmeralda', hex: '#50C878' },
  { name: 'Azul zafiro', hex: '#0F52BA' },
  { name: 'Rojo escarlata', hex: '#FF2400' },
  { name: 'Amarillo mostaza', hex: '#FFDB58' },
  { name: 'Púrpura', hex: '#800080' },
  { name: 'Azul cobalto', hex: '#0047AB' },
  { name: 'Verde menta', hex: '#98FF98' },
  { name: 'Rosa mexicano', hex: '#E4007C' },
  { name: 'Marrón chocolate', hex: '#D2691E' },
  { name: 'Gris claro', hex: '#D3D3D3' },
  { name: 'Azul petróleo', hex: '#013220' },
  { name: 'Verde bosque', hex: '#228B22' },
  { name: 'Azul celeste', hex: '#B0E0E6' },
  { name: 'Rojo vino', hex: '#722F37' },
  { name: 'Amarillo limón', hex: '#FFF700' },
  { name: 'Verde pistacho', hex: '#93C572' },
  { name: 'Rosa pastel', hex: '#FFD1DC' },
  { name: 'Marrón claro', hex: '#A52A2A' },
  { name: 'Gris oscuro', hex: '#A9A9A9' },
  { name: 'Verde oliva oscuro', hex: '#556B2F' },
  { name: 'Azul real', hex: '#4169E1' },
  { name: 'Rojo tomate', hex: '#FF6347' },
  { name: 'Amarillo dorado', hex: '#FFD700' },
  { name: 'Lila', hex: '#C8A2C8' },
  { name: 'Canela', hex: '#7B3F00' },
  { name: 'Marfil', hex: '#FFFFF0' },
  { name: 'Azul iceberg', hex: '#71A6D2' },
  { name: 'Verde jade', hex: '#00A86B' },
  { name: 'Cobre', hex: '#B87333' },
  { name: 'Aguamarina', hex: '#7FFFD4' },
  { name: 'Fucsia', hex: '#FF00FF' },
  { name: 'Púrpura oscuro', hex: '#301934' },
  { name: 'Gris humo', hex: '#708090' },
  { name: 'Crema', hex: '#FFFDD0' },
  { name: 'Beige', hex: '#F5F5DC' },
  { name: 'Verde musgo', hex: '#8A9A5B' },
  { name: 'Verde agua', hex: '#00CED1' },
  { name: 'Azul denim', hex: '#1560BD' },
  { name: 'Mostaza', hex: '#FFDB58' },
  { name: 'Granate', hex: '#800000' },
  { name: 'Terracota', hex: '#E2725B' },
  { name: 'Café', hex: '#6F4E37' },
  { name: 'Caoba', hex: '#C04000' },
  { name: 'Amaranto', hex: '#E52B50' },
  { name: 'Orquídea', hex: '#DA70D6' },
  { name: 'Zanahoria', hex: '#ED9121' },
  { name: 'Sandía', hex: '#FC6C85' },
  { name: 'Esmeralda', hex: '#50C878' },
  { name: 'Cian oscuro', hex: '#008B8B' },
  { name: 'Turquesa claro', hex: '#AFEEEE' },
  { name: 'Fucsia claro', hex: '#FF77FF' },
  { name: 'Lima', hex: '#BFFF00' },
  { name: 'Verde militar', hex: '#4B5320' },
  { name: 'Rosa coral', hex: '#F88379' },
  { name: 'Malva', hex: '#B57EDC' },
  { name: 'Lavanda gris', hex: '#C4C3D0' },
  { name: 'Verde neón', hex: '#39FF14' },
  { name: 'Amarillo neón', hex: '#FFF700' },
  { name: 'Azul neón', hex: '#1F51FF' },
  { name: 'Rosa neón', hex: '#FF6EC7' },
  { name: 'Turquesa neón', hex: '#0FF0FC' },
  { name: 'Naranja neón', hex: '#FF5F1F' },
  { name: 'Rojo neón', hex: '#FF3131' },
  { name: 'Azul eléctrico', hex: '#7DF9FF' },
  { name: 'Azul noche', hex: '#003366' },
  { name: 'Verde selva', hex: '#29AB87' },
  { name: 'Amarillo pálido', hex: '#FFFFE0' },
  { name: 'Menta clara', hex: '#AAF0D1' },
  { name: 'Azul pastel', hex: '#AEC6CF' },
  { name: 'Rosa pálido', hex: '#FFD1DC' },
  { name: 'Gris perla', hex: '#C0C0C0' },
  { name: 'Verde hoja', hex: '#228B22' },
  { name: 'Azul océano', hex: '#4F42B5' },
  { name: 'Tierra', hex: '#E1A95F' },
  { name: 'Bronce', hex: '#CD7F32' },
  { name: 'Carbón', hex: '#36454F' },
  { name: 'Nuez', hex: '#CD853F' },
  { name: 'Ladrillo', hex: '#B22222' },
  { name: 'Rojo quemado', hex: '#8A0707' },
  { name: 'Durazno', hex: '#FFE5B4' },
  { name: 'Mandarina', hex: '#F28500' },
  { name: 'Ámbar', hex: '#FFBF00' },
  { name: 'Chocolate', hex: '#7B3F00' },
  { name: 'Verde cactus', hex: '#588157' },
  { name: 'Azul grisáceo', hex: '#6699CC' },
  { name: 'Celeste suave', hex: '#B2FFFF' },
  { name: 'Verde agua marina', hex: '#76EEC6' },
  { name: 'Rosa brillante', hex: '#FF007F' },
  { name: 'Ocre', hex: '#CC7722' },
  { name: 'Verde botella', hex: '#006A4E' },
  { name: 'Azul tinta', hex: '#003153' },
  { name: 'Arena', hex: '#C2B280' },
  { name: 'Perla', hex: '#EAE0C8' },
  { name: 'Azul ártico', hex: '#D0F0C0' },
  { name: 'Rubí', hex: '#E0115F' },
  { name: 'Topacio', hex: '#FFC87C' },
  { name: 'Zafiro claro', hex: '#7EC8E3' },
  { name: 'Gris azulado', hex: '#6699CC' },
  { name: 'Azul lavanda', hex: '#E6E6FA' },
  { name: 'Cuarzo', hex: '#D9D6CF' },
  { name: 'Verde palmera', hex: '#20392C' },
  { name: 'Rojo amapola', hex: '#E34234' },
  { name: 'Azul tormenta', hex: '#4A646C' },
  { name: 'Verde jade oscuro', hex: '#00A36C' },
  { name: 'Rojo coralino', hex: '#FF4040' },
  { name: 'Fucsia fuerte', hex: '#FF00AF' },
  { name: 'Gris niebla', hex: '#B4B4B4' },
  { name: 'Azul glacial', hex: '#74BBFB' },
  { name: 'Verde pradera', hex: '#7BB661' },
  { name: 'Amarillo mango', hex: '#FDBE02' },
  { name: 'Turquesa profundo', hex: '#00CED1' },
  { name: 'Azul cosmos', hex: '#2E3A59' },
  { name: 'Verde pasto', hex: '#7CFC00' },
  { name: 'Cereza', hex: '#DE3163' },
  { name: 'Rojo Ferrari', hex: '#FF2800' },
  { name: 'Avena', hex: '#F5DEB3' },
  { name: 'Verde manzana', hex: '#8DB600' },
  { name: 'Azul glacial claro', hex: '#CCFFFF' },
  { name: 'Rojo rubí', hex: '#9B111E' },
  { name: 'Gris piedra', hex: '#8B8C89' },
  { name: 'Azul pizarra', hex: '#6A5ACD' },
  { name: 'Turquesa tropical', hex: '#00F5FF' },
  { name: 'Verde perico', hex: '#C4D300' },
  { name: 'Coral suave', hex: '#F08080' },
  { name: 'Rojo ladrillo', hex: '#B22222' },
  { name: 'Lima', hex: '#BFFF00' },
  { name: 'Verde neón', hex: '#39FF14' },
  { name: 'Azul eléctrico', hex: '#7DF9FF' },
  { name: 'Fucsia brillante', hex: '#D500F9' },
  { name: 'Amarillo fluorescente', hex: '#CCFF00' },
  { name: 'Rosa fluorescente', hex: '#FF1493' },
  { name: 'Naranja neón', hex: '#FF5F1F' },
  { name: 'Púrpura vibrante', hex: '#9B30FF' },
  { name: 'Naranja atardecer', hex: '#FF4500' },
  { name: 'Lima intenso', hex: '#D8FF33' },
  { name: 'Púrpura eléctrico', hex: '#BF00FF' },
  { name: 'Aqua brillante', hex: '#00FFFF' },
  { name: 'Rosa magenta', hex: '#FF00FF' },
  { name: 'Azul cielo', hex: '#87CEFA' },
  { name: 'Rojo intenso', hex: '#FF6347' },
  { name: 'Violeta intenso', hex: '#5F4B8B' },
  { name: 'Coral claro', hex: '#F08080' },
  { name: 'Rosa neón', hex: '#FF69B4' },
  { name: 'Cáscara de naranja', hex: '#FFA500' },
  { name: 'Azul neón', hex: '#1F51FF' },
  { name: 'Azul ultramar', hex: '#3F48CC' },
  { name: 'Amarillo brillante', hex: '#FFFF00' },
  { name: 'Verde fosforescente', hex: '#00FF00' },
  { name: 'Rojo neón', hex: '#FF3131' },
  { name: 'Verde esmeralda', hex: '#50C878' },
  { name: 'Lima eléctrico', hex: '#00FF7F' },
  { name: 'Niebla púrpura', hex: '#8A2BE2' },
  { name: 'Amarillo canario', hex: '#FFFF99' },
  { name: 'Verde ácido', hex: '#7FFF00' },
  { name: 'Vino', hex: '#800000' },
  { name: 'Rosa pastel', hex: '#FFD1DC' },
  { name: 'Ocre', hex: '#CC7722' },
  { name: 'Verde bosque', hex: '#228B22' },
  { name: 'Rosa antiguo', hex: '#C08081' },
  { name: 'Rojo anaranjado', hex: '#FF4500' },
  { name: 'Naranja quemado', hex: '#FF7F32' },
  { name: 'Azul plomo', hex: '#6A5ACD' },
  { name: 'Lavanda', hex: '#E6E6FA' },
  { name: 'Gris pálido', hex: '#D3D3D3' },
  { name: 'Cielo pastel', hex: '#B0E0E6' },
  { name: 'Café claro', hex: '#C9A57B' },
  { name: 'Verde pasto', hex: '#7CFC00' },
  { name: 'Azul marino', hex: '#000080' },
  { name: 'Tierra', hex: '#E1A95F' },
  { name: 'Gris oscuro', hex: '#A9A9A9' },
  { name: 'Rosa fucsia', hex: '#FF007F' },
  { name: 'Verde oliva', hex: '#808000' },
  { name: 'Rosa suave', hex: '#F9A7B0' },
  { name: 'Amarillo mostaza', hex: '#FFDB58' },
  { name: 'Rojo púrpura', hex: '#800080' },
  { name: 'Azul tormenta', hex: '#4A646C' },
  { name: 'Rosa claro', hex: '#FFB6C1' },
  { name: 'Turquesa', hex: '#40E0D0' },
  { name: 'Borgoña', hex: '#800020' },
  { name: 'Lila', hex: '#C8A2C8' },
  { name: 'Naranja cálido', hex: '#FF6F00' },
  { name: 'Beige claro', hex: '#F5F5DC' },
  { name: 'Ocre dorado', hex: '#CCA300' },
  { name: 'Rojo pálido', hex: '#FA8072' },
  { name: 'Marrón miel', hex: '#D25A00' },
  { name: 'Verde albahaca', hex: '#2F6A4F' },
  { name: 'Menta', hex: '#98FF98' },
  { name: 'Amarillo primaveral', hex: '#FFFF66' },
  { name: 'Lavanda clara', hex: '#E4E4F0' },
  { name: 'Rosa melocotón', hex: '#FAD6A5' },
  { name: 'Marfil', hex: '#FFFFF0' },
  { name: 'Café oscuro', hex: '#4B3621' },
  { name: 'Piedra', hex: '#C0C0C0' },
  { name: 'Verde musgo', hex: '#8A9A5B' },
  { name: 'Gris acero', hex: '#8A8D8F' },
  { name: 'Vino tinto', hex: '#B83B5E' },
  { name: 'Cyan claro', hex: '#66FFFF' },
  { name: 'Bamboo', hex: '#D8C774' },
  { name: 'Gris plomo', hex: '#A9A9A9' },
  { name: 'Mandarina', hex: '#FF6600' },
  { name: 'Naranja claro', hex: '#FFD700' },
  { name: 'Ambar', hex: '#FFBF00' },
  { name: 'Verde jade', hex: '#00A86B' },
  { name: 'Turquesa suave', hex: '#AFEEEE' },
  { name: 'Café oscuro', hex: '#6F4E37' },
  { name: 'Piedra gris', hex: '#696969' },
  { name: 'Naranja sandía', hex: '#FF8C00' },
  { name: 'Gris pardo', hex: '#9E9E9E' },
  { name: 'Azul celeste', hex: '#B0E0E6' },
  { name: 'Salmón claro', hex: '#FFA07A' },
  { name: 'Azul océano', hex: '#4F42B5' },
  { name: 'Violeta pálido', hex: '#B57EDC' },
  { name: 'Rojo coral', hex: '#FF4040' },
  { name: 'Gris humo', hex: '#708090' },
  { name: 'Café tostado', hex: '#9E7A4E' },
  { name: 'Verde esmeralda oscuro', hex: '#2E8B57' },
  { name: 'Siena', hex: '#882D17' },
  { name: 'Morado claro', hex: '#9A4E97' },
  { name: 'Verde campo', hex: '#6B8E23' },
  { name: 'Verde pistacho', hex: '#93C572' },
  { name: 'Magenta claro', hex: '#FF77FF' },
  { name: 'Marrón claro', hex: '#A52A2A' },
  { name: 'Aguamarina suave', hex: '#66CDAA' },
  { name: 'Verde seco', hex: '#556B2F' },
  { name: 'Cobalto', hex: '#0047AB' },
  { name: 'Cian oscuro', hex: '#008B8B' },
  { name: 'Rosa coral', hex: '#F88379' },
  { name: 'Nuez', hex: '#CD853F' },
  { name: 'Turquesa profundo', hex: '#00CED1' },
  { name: 'Perla', hex: '#EAE0C8' },
  { name: 'Zafiro', hex: '#0F52BA' },
  { name: 'Gris cálido', hex: '#A39D91' },
  { name: 'Naranja suave', hex: '#FFA07A' },
  { name: 'Chocolate', hex: '#7B3F00' },
  { name: 'Durazno', hex: '#FFE5B4' },
  { name: 'Verde militar', hex: '#4B5320' },
  { name: 'Vino rosado', hex: '#9B111E' },
  { name: 'Rosa pastel', hex: '#FFD1DC' },
  { name: 'Ocaso', hex: '#FF9B8D' },
  { name: 'Verde claro', hex: '#B9E1A6' },
  { name: 'Lavanda gris', hex: '#C4C3D0' },
  { name: 'Rosa pastel', hex: '#F8C8DC' },
  { name: 'Oro viejo', hex: '#B08D57' },
  { name: 'Pistacho', hex: '#93C572' },
  { name: 'Verde césped', hex: '#7CFC00' },
  { name: 'Beige oscuro', hex: '#D8BFD8' },
  { name: 'Amarillo pálido', hex: '#FFFFE0' },
  { name: 'Verde bosque claro', hex: '#B5EAAA' },
  { name: 'Amarillo suave', hex: '#FFFAE6' },
  { name: 'Azul pastel', hex: '#AEC6CF' },
  { name: 'Café oscuro', hex: '#3E2723' },
  { name: 'Naranja suave', hex: '#F9A825' },
  { name: 'Aqua oscuro', hex: '#006E6D' },
  { name: 'Verde olivo claro', hex: '#9B9E2A' },
  { name: 'Azul cielo claro', hex: '#87CEFA' },
  { name: 'Lavanda claro', hex: '#E6E6FA' },
  { name: 'Rojo canela', hex: '#9E2A2F' },
  { name: 'Rosa oscuro', hex: '#C71585' },
  { name: 'Gris antracita', hex: '#2F2F2F' },
  { name: 'Verde esmeralda claro', hex: '#64C18D' },
  { name: 'Azul celeste claro', hex: '#A4D8E0' },
  { name: 'Turquesa oscuro', hex: '#008B8B' },
  { name: 'Rosa neón claro', hex: '#FF77FF' },
  { name: 'Lila oscuro', hex: '#8A2BE2' },
  { name: 'Vino claro', hex: '#9B111E' },
  { name: 'Ocre claro', hex: '#E1A95F' },
  { name: 'Cian claro', hex: '#00FFFF' },
  { name: 'Granate oscuro', hex: '#9B111E' },
  { name: 'Morado intenso', hex: '#8A2BE2' },
  { name: 'Verde esmeralda oscuro', hex: '#50C878' },
  { name: 'Azul noche claro', hex: '#003366' },
  { name: 'Rosa chicle', hex: '#FC64A1' },
  { name: 'Naranja pálido', hex: '#FFB74D' },
  { name: 'Beige rosado', hex: '#F5F5DC' },
  { name: 'Rojo claro', hex: '#FF8C00' },
  { name: 'Azul marino claro', hex: '#00008B' },
  { name: 'Azul pálido', hex: '#B0E0E6' },
  { name: 'Lavanda gris', hex: '#C4C3D0' },
  { name: 'Verde oliva claro', hex: '#B5B35C' },
  { name: 'Rosa coral claro', hex: '#FF7F50' },
  { name: 'Verde pasto claro', hex: '#98FB98' },
  { name: 'Gris cálido', hex: '#D3D3D3' },
  { name: 'Berenjena', hex: '#6A4E4D' },
  { name: 'Café oscuro claro', hex: '#3E2723' },
  { name: 'Amarillo dorado claro', hex: '#FFD700' },
  { name: 'Turquesa suave', hex: '#40E0D0' },
  { name: 'Rosa coral oscuro', hex: '#F88379' },
  { name: 'Naranja rosado', hex: '#FF6F00' },
  { name: 'Cielo azul claro', hex: '#87CEEB' },
  { name: 'Verde jungla', hex: '#29AB87' },
  { name: 'Rosa brillante claro', hex: '#FF007F' },
  { name: 'Lima brillante', hex: '#BFFF00' },
  { name: 'Amarillo mostaza claro', hex: '#FFDB58' },
  { name: 'Rojo marino', hex: '#B22222' },
  { name: 'Celeste pálido', hex: '#B2FFFF' },
  { name: 'Rosa fuerte', hex: '#FF1493' },
  { name: 'Azul oscuro claro', hex: '#1F51FF' },
];
